global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-enterprise-accelerator-msservers
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
#    - sa-east-1 NAT Gateway not available
    - us-east-1
    - us-west-1
    - us-west-2
  reporting: true
tests:
  master:
    template_file: msservers-master.template
    parameter_input: msservers-master.json
